import { useState } from 'react';
import { X, Plus } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { DocumentPanel } from '../../doc-viewer/ui/DocumentPanel';
import { documentApi } from '../../doc-viewer/api/documentApi';
import type { Issue } from '../api/issueApi';

interface IssueDetailModalProps {
  issue: Issue;
  onClose: () => void;
}

export function IssueDetailModal({ issue, onClose }: IssueDetailModalProps) {
  const [activeTab, setActiveTab] = useState<'info' | 'documents'>('info');
  const [isCreatingDoc, setIsCreatingDoc] = useState(false);
  const [newDocType, setNewDocType] = useState('design');
  const [newDocLlm, setNewDocLlm] = useState('claude');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const queryClient = useQueryClient();

  const handleCreateDocument = async () => {
    try {
      setIsSubmitting(true);
      await documentApi.createIssueDocument(issue.id, {
        type: newDocType,
        llm: newDocLlm,
        content: `# ${issue.title} - ${newDocType}\n\nGenerated by ${newDocLlm}\n\n## Overview\n\n`,
      });

      // Invalidate file tree query to refresh the list
      queryClient.invalidateQueries({ queryKey: ['fileTree', issue.id] });

      setIsCreatingDoc(false);
    } catch (error) {
      console.error('Failed to create document:', error);
      alert('Failed to create document');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="bg-gray-900 rounded-lg shadow-xl w-full max-w-6xl h-[85vh] flex flex-col relative">
        {/* Creation Modal Overlay */}
        {isCreatingDoc && (
          <div className="absolute inset-0 z-10 bg-black/80 flex items-center justify-center rounded-lg">
            <div className="bg-gray-800 p-6 rounded-lg shadow-lg w-96 border border-gray-700">
              <h3 className="text-lg font-semibold text-white mb-4">Create New Document</h3>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">Document Type</label>
                  <select
                    value={newDocType}
                    onChange={(e) => setNewDocType(e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded px-3 py-2 text-white focus:outline-none focus:border-blue-500"
                  >
                    <option value="design">Design</option>
                    <option value="requirements">Requirements</option>
                    <option value="api">API Spec</option>
                    <option value="test">Test Plan</option>
                    <option value="review">Code Review</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">LLM Model</label>
                  <select
                    value={newDocLlm}
                    onChange={(e) => setNewDocLlm(e.target.value)}
                    className="w-full bg-gray-900 border border-gray-700 rounded px-3 py-2 text-white focus:outline-none focus:border-blue-500"
                  >
                    <option value="claude">Claude</option>
                    <option value="gpt4">GPT-4</option>
                    <option value="gemini">Gemini</option>
                  </select>
                </div>

                <div className="pt-2 flex justify-end gap-2">
                  <button
                    onClick={() => setIsCreatingDoc(false)}
                    className="px-4 py-2 text-sm text-gray-400 hover:text-white transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleCreateDocument}
                    disabled={isSubmitting}
                    className="px-4 py-2 text-sm bg-blue-600 hover:bg-blue-500 text-white rounded transition-colors disabled:opacity-50"
                  >
                    {isSubmitting ? 'Creating...' : 'Create'}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-700">
          <div className="flex-1">
            <h2 className="text-xl font-semibold text-white">{issue.title}</h2>
            <div className="flex items-center gap-3 mt-2">
              <span className="text-xs font-medium px-2 py-1 rounded bg-gray-800 text-gray-300">
                {issue.type}
              </span>
              <span
                className={`text-xs px-2 py-1 rounded ${issue.priority === 'high'
                  ? 'bg-red-900/30 text-red-400'
                  : issue.priority === 'medium'
                    ? 'bg-yellow-900/30 text-yellow-400'
                    : 'bg-green-900/30 text-green-400'
                  }`}
              >
                {issue.priority}
              </span>
              <span className="text-xs px-2 py-1 rounded bg-blue-900/30 text-blue-400">
                {issue.status}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {activeTab === 'documents' && (
              <button
                onClick={() => setIsCreatingDoc(true)}
                className="flex items-center gap-2 px-3 py-1.5 bg-blue-600/20 text-blue-400 hover:bg-blue-600/30 rounded text-sm transition-colors border border-blue-600/30"
              >
                <Plus size={16} />
                New Document
              </button>
            )}

            <button
              onClick={onClose}
              className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
              aria-label="Close modal"
            >
              <X size={20} className="text-gray-400" />
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-700 px-6">
          <button
            onClick={() => setActiveTab('info')}
            className={`px-4 py-3 text-sm font-medium transition-colors relative ${activeTab === 'info'
              ? 'text-blue-400'
              : 'text-gray-400 hover:text-gray-300'
              }`}
          >
            기본 정보
            {activeTab === 'info' && (
              <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-400" />
            )}
          </button>
          <button
            onClick={() => setActiveTab('documents')}
            className={`px-4 py-3 text-sm font-medium transition-colors relative ${activeTab === 'documents'
              ? 'text-blue-400'
              : 'text-gray-400 hover:text-gray-300'
              }`}
          >
            문서
            {activeTab === 'documents' && (
              <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-400" />
            )}
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-hidden">
          {activeTab === 'info' ? (
            <div className="p-6 overflow-y-auto h-full">
              <div className="space-y-6">
                {/* Description */}
                {issue.description && (
                  <div>
                    <h3 className="text-sm font-medium text-gray-400 mb-2">
                      설명
                    </h3>
                    <p className="text-gray-200 whitespace-pre-wrap">
                      {issue.description}
                    </p>
                  </div>
                )}

                {/* Metadata */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <h3 className="text-sm font-medium text-gray-400 mb-2">
                      생성일
                    </h3>
                    <p className="text-gray-200">
                      {new Date(issue.createdAt).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <h3 className="text-sm font-medium text-gray-400 mb-2">
                      수정일
                    </h3>
                    <p className="text-gray-200">
                      {new Date(issue.updatedAt).toLocaleString()}
                    </p>
                  </div>
                  {issue.docPath && (
                    <div>
                      <h3 className="text-sm font-medium text-gray-400 mb-2">
                        문서 경로
                      </h3>
                      <p className="text-gray-200 font-mono text-xs">
                        {issue.docPath}
                      </p>
                    </div>
                  )}
                  {issue.branchName && (
                    <div>
                      <h3 className="text-sm font-medium text-gray-400 mb-2">
                        브랜치명
                      </h3>
                      <p className="text-gray-200 font-mono text-xs">
                        {issue.branchName}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ) : (
            <div className="h-full">
              <DocumentPanel issueId={issue.id} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
